name: Detect changes
description: This action detects relevant changes in repo.

inputs:
  base:
    description: Base commit for diff.
    default: origin/main
  commit:
    description: Commit to compare with base.
    default: HEAD
  fetch_depth:
    description: git fetch depth. 0 indicates all.
    default: '100'
  filters:
    description: Paths to relevant files
    required: true
outputs:
  result:
    description: thing
    value: ${{ steps.changes.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Get changes
      id: changes
      env:
        BASE: ${{ inputs.base }}
        COMMIT: ${{ inputs.commit }}
        FETCH_DEPTH: ${{ inputs.fetch_depth }}
        FILTERS: ${{ inputs.filters }}
      run: bash get_changes.sh
      shell: bash
