name: Linting

on: push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v3

      - id: cache-yamllint
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: /usr/local/bin/yamllint
          key: yamllint-${{ runner.os }}
          restore-keys: shellcheck-stable-${{ runner.os }}

      - if: ${{ steps.cache-yamllint.outputs.cache-hit != 'true' }}
        name: Install yamllint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install yamllint

      - name: Run yamllint
        shell: bash
        run: yamllint .

      - id: cache-shellcheck
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: shellcheck
          key: shellcheck-stable-${{ runner.os }}
          restore-keys: shellcheck-stable-${{ runner.os }}

      - if: ${{ steps.cache-shellcheck.outputs.cache-hit != 'true' }}
        name: Download shellcheck
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            osvariant="darwin"
          else
            osvariant="linux"
          fi
          baseurl="https://github.com/koalaman/shellcheck/releases/download"
          curl -Lso "sc.tar.xz" \
            "${baseurl}/stable/shellcheck-stable.${osvariant}.x86_64.tar.xz"

          tar -xf "sc.tar.xz"

          mv "shellcheck-stable/shellcheck" "shellcheck"

      - name: Run ShellCheck
        shell: bash
        run: |
          echo "Running shellcheck"
          for file in $(find **/*.sh -type f); do
            echo "- $file"
            ./shellcheck $file;
          done;
