name: Linting

on: push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        id: cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: shellcheck
          key: shellcheck-stable-${{ runner.os }}
          restore-keys: shellcheck-stable-${{ runner.os }}

      #- id: yaml-lint
      #  uses: ibiqlik/action-yamllint@v3

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Download shellcheck
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            osvariant="darwin"
          else
            osvariant="linux"
          fi
          baseurl="https://github.com/koalaman/shellcheck/releases/download"
          curl -Lso "sc.tar.xz" \
            "${baseurl}/stable/shellcheck-stable.${osvariant}.x86_64.tar.xz"
          
          tar -xf "sc.tar.xz"
          
          mv "shellcheck-stable/shellcheck" "shellcheck"

      - name: Run ShellCheck
        shell: bash
        run: |
          echo "Running shellcheck"
          for file in $(find **/*.sh -type f); do
            echo "- $file"
            ./shellcheck $file;
          done;
