name: Linting

on: push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v3
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
