name: Testing

on: push

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - id: tests
        run: bash tests/tests.sh
