name: Test injection

on: push

jobs:
  test-injection:
    name: Detect changes
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - id: detect
        uses: ./
        with:
          base: origin/main & echo "fail"
          commit: HEAD & echo "fail"
          filters: |
            
            md: **/*.md
            
            yml: **/*.yaml|**/*.yml
            
            
            $(echo "hey")
            
            test_injection: **/*.yaml|**/*.yml"; echo ""; echo "
          

      - name: Check detect outputs
        run: |
          echo "any ${{ steps.detect.outputs.has_any_changes }}"
          echo "changes ${{ steps.detect.outputs.changes }}"
          echo "yml ${{ steps.detect.outputs.yml }}"
          echo "yml ${{ steps.detect.outputs.yml_files }}"
          echo "yml ${{ steps.detect.outputs.yml_count }}"
          echo "md  ${{ steps.detect.outputs.md }}"
          echo "md  ${{ steps.detect.outputs.md_files }}"
          echo "md ${{ steps.detect.outputs.md_count }}"
          echo "no  ${{ steps.detect.outputs.missing }}"
          echo "no  ${{ steps.detect.outputs.missing_files }}"
          echo "no ${{ steps.detect.outputs.missing_count }}"
